import "./globals.css";
import Provider from "@/components/SessionProvider";
import NavigationBar from "@/components/NavigationBar";
import { Toaster } from "sonner";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "13th NPLC - Competitive Programming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavigationBar />
          {children}
          <Toaster
            position="bottom-right"
            theme="dark"
            richColors
            duration={5000}
            toastOptions={{
              classNames: {
                toast: "h-24 text-lg gap-4",
                title: "text-lg font-bold",
                description: "text-base",
                actionButton: "text-base",
                cancelButton: "text-base",
                icon: "size-8 flex-shrink-0",
              },
              style: {
                fontSize: "16px",
                padding: "20px",
                borderRadius: "8px",
                gap: "16px",
              },
            }}
          />
        </Provider>
      </body>
    </html>
  );
}
