import "./globals.css";
import Toast from "@/components/layout/Toast";
import Background from "@/components/layout/Background";
import Provider from "@/components/layout/SessionProvider";
import NavigationBar from "@/components/layout/NavigationBar";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "13th NPLC - Competitive Programming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative bg-gradient-to-b from-[#111114] to-[#090A1E] overflow-x-hidden`}
      >
        <Background />
        <Provider>
          <NavigationBar />
          <div className="min-h-screen flex flex-col justify-center items-center">
            {children}
          </div>
          <Toast />
        </Provider>
      </body>
    </html>
  );
}
