import "./globals.css";
import Provider from "@/components/SessionProvider";
import NavigationBar from "@/components/NavigationBar";
import { Toaster } from "sonner";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "13th NPLC - Competitive Programming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavigationBar />
          {children}
          <Toaster
            position="bottom-right"
            theme="dark"
            richColors
            duration={5000}
          />
        </Provider>
      </body>
    </html>
  );
}
